# zndq.appveyor

environment:
  version: 20180409
  affix: zndq

platform:
# By default, it's the AMD64(/x64) version of PHP which is installed.
# Have to search how to change this.
# - x86
- x64

configuration: Release

os :
# - Visual Studio 2017
- Visual Studio 2015
# - Visual Studio 2013

# https://help.appveyor.com/discussions/problems/5616-not-able-to-build-due-to-problem-in-chocolateyinstallps1#comment_41949965
install: 
- ps: Set-Service wuauserv -StartupType Manual
- cinst -y php --version 7.1.11

before_build:
# Setting environment variables for the PHP build procedure.
- call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
- dir
- dir C:\tools\php71
- dir C:\tools\php71\dev
# Retrieving and installing PHP source code.
- curl -L https://github.com/php/php-src/archive/php-7.1.10.tar.gz --output php.tgz
- 7z x php.tgz
- 7z x php.tar
# Creation of some files needed by the compilation of the extension
- cd php-src-php-7.1.10
- buildconf.bat --add-modules-dir=c:\projects\zndq
- configure.bat
# We do not build from the source (no 'nmake'), as we use the already installed PHP binaries.
# 'buildconf.bat' and 'configure.bat' are only launched to generate some files needed
# to compile the extension (namely 'main/config.w32.h').
- dir
- cd ..

test_script:
- echo "***** 'ZNDq' TEST BEGIN *****" && C:\tools\php71\php -dextension=./zndq.dll test.php && echo "***** 'ZNDq' TEST END *****"

# matrix:
  # allow_failures:
  # - os: Visual Studio 2017
  
skip_tags: true  
  
after_build:
# .zip part
- echo | set /p="%affix%-v%version%" >tmpfile.tmp || true
- echo | set /p="-win-" >>tmpfile.tmp || true
- echo | set /p="%platform%" >>tmpfile.tmp || true
- set /p target= <tmpfile.tmp
- echo .%target%.
- set dir=%target%
- mkdir %dir%
- copy %affix%.dll %dir%
- 7z a %target%.zip %dir%
# '.tar.gz' part (for NPM installation : 'node-pre-gyp')
- if "%platform%"=="x86" set platform=ia32
- echo | set /p="%affix%-v%version%" >tmpfile.tmp || true
- echo | set /p="-win32-" >>tmpfile.tmp || true
- echo | set /p="%platform%" >>tmpfile.tmp || true
- set /p addon= <tmpfile.tmp
- echo .%addon%.
- set dir=win32-%platform%
- mkdir %dir%
- copy %affix%.dll %dir%
# It MUST be '.tar.gz' to be retrieved by 'node-pre-gyp' when installed with 'npm' !
- 7z a -ttar -so dummy %dir% | 7z a -si %addon%.tar.gz

artifacts:
- name: zip
  path: '*.zip'
- name: tgz
  path: '*.tar.gz'


deploy:
  - provider: GitHub
    tag: v$(version)
    description: ''
    auth_token:
      secure: kKebvPLjikQbZ7E1Vm8omoYc9K0wOcKxjWsglp3+D4fV9ev/FaWr8ZBI+AseOTis
    draft: false
    prerelease: false
    artifact: tgz
    on:
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

  - provider: GitHub
    tag: v$(version)
    description: ''
    auth_token:
      secure: kKebvPLjikQbZ7E1Vm8omoYc9K0wOcKxjWsglp3+D4fV9ev/FaWr8ZBI+AseOTis
    draft: false
    prerelease: false
    artifact: zip
    on:
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

