# zndq.travis

os:
- linux
# - osx

#dist: trusty

language: php

php:
- "7.1"

script:
- phpize
- ./configure
- make -j
- php -dextension=modules/zndq.so test.php

# To disable building on tags. Tags are supposed to begin with 'v' and only containing digits.
branches:
  except:
    - /^v[0-9]/
